version: "3.8"

services:
  db:
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: widgets
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    volumes:
      - ./init:/docker-entrypoint-initdb.d
#docker-compose exec -T db pg_dumpall -U user --database widgets --data-only > dump.sql
